package com.example.rammzexpensetracker.ui.dashboard;

import java.util.HashMap;
import java.util.Map;

public class Budget {

    String key;
    double budget, totalExpenses;
    Map<String, Double> amountInCategory = new HashMap<>();

    // Empty constructor needed for Firebase
    public Budget() {
    }

    // Getter functions for each entry box

    public double getTotalExpenses() {
        return totalExpenses;
    }

    public Map<String, Double> getAmountInCategory() { return amountInCategory; }

    public double getBudget() {
        return budget;
    }

    // gets unique key generated by Firebase
    public String getKey() {
        return key;
    }

    // Setter functions for each entry box variable

    public void setTotalExpenses(double totalExpenses) {
        this.totalExpenses = totalExpenses;
    }

    public void setBudget(double budget) { this.budget = budget; }
    public void setAmountInCategory(Map<String, Double> amountInCategory) { this.amountInCategory = amountInCategory; }

    public void setKey(String key) {
        this.key = key;
    }

}
